import tcod

LIMIT_FPS = 20

SCREEN_WIDTH = 80
SCREEN_HEIGHT = 50

MAP_WIDTH = 80
MAP_HEIGHT = 43

ROOM_MAX_SIZE = 10
ROOM_MIN_SIZE = 6
ROOM_COUNT = 30

FOV_ALGORITHM = 0
FOV_LIGHT_WALLS = True
FOV_RADIUS = 10

COLOR_DARK_WALL = tcod.Color(0, 0, 100)
COLOR_DARK_GROUND = tcod.Color(50, 50, 150)
COLOR_LIGHT_WALL = tcod.Color(130, 110, 50)
COLOR_LIGHT_GROUND = tcod.Color(200, 180, 50)

COLOR_DARKNESS = tcod.COLOR_BLACK
COLOR_LABEL = tcod.COLOR_BLUE

COLOR_ORC = tcod.COLOR_DESATURATED_GREEN
COLOR_TROLL = tcod.COLOR_DARKER_GREEN
COLOR_REMAINS = tcod.COLOR_DARK_RED

COLOR_GUI_FOREGROUND = tcod.COLOR_WHITE

MAX_ROOM_MONSTERS = 5
MAX_ROOM_ITEMS = 2

ACTION_NONE = 0
ACTION_MOVE = 1
ACTION_EXIT = 2

BAR_WIDTH = 20

PANEL_HEIGHT = SCREEN_HEIGHT - MAP_HEIGHT
PANEL_Y = SCREEN_HEIGHT - PANEL_HEIGHT
PANEL_BACKGROUND = tcod.COLOR_BLACK
PANEL_BAR_BACK = tcod.COLOR_DARKER_RED
PANEL_BAR_COLOR = tcod.COLOR_LIGHT_RED
PANEL_TEXT_COLOR = tcod.COLOR_WHITE

PANEL_MSG_X = BAR_WIDTH + 2
MSG_WIDTH = SCREEN_WIDTH - BAR_WIDTH - 2
MSG_HEIGHT = PANEL_HEIGHT - 1

INVENTORY_WIDTH = 50

HEAL_AMOUNT = 4

# Bitwise item.on_use return values
ITEM_USE_CANCELLED = 1
ITEM_USE_DESTROY = 2
